[package]
name = "proposal-hooks"
version = "0.1.0"
edition = "2021"
description = "DAO DAO v1 proposal hooks."
license = "Apache-2.0"
repository = "https://github.com/DA0-DA0/dao-contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cosmwasm-std = "1.0.0"
indexable-hooks = { version = "0.1.0", path = "../indexable-hooks" }
