[package]
name = "cw20-vest"
version = "0.1.0"
authors = ["Teddy Knox <teddy@stake.fish>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []


[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = "1.1.3"
cw-storage-plus = "0.13"
cw2 = "0.13"
cw20 = "0.13"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
cw-utils = "0.13"
cw20-stake = { path = "../../staking/cw20-stake" }
cw-controllers = "0.13"
cw20-base = {  version = "0.13", features = ["library"] }

[dev-dependencies]
cw-multi-test = {  version = "0.13" }
anyhow = "1.0.65"
