[package]
name = "cw-msg-filter"
authors = ["Jake Hartnell <donotemail@please.com>"]
description = "A package to filter CosmWasm messages."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true, features = ["staking"] }
cosmwasm-schema = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
