[package]
name = "cw-core-macros"
version = "0.1.0"
edition = "2021"
description = "DAO DAO v1 macros."
license = "Apache-2.0"
repository = "https://github.com/DA0-DA0/dao-contracts"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
