[package]
name = "native-stake"
version = "2.0.3"
authors = ["mccallofthewild <mccallofthewild@users.noreply.github.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/DA0-DA0/dao-contracts/contracts/staking/native-stake"
description = "Staking contract for native Cosmos SDK tokens. Staked balances can be queried at any height."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-controllers = { workspace = true }
cw20 = { workspace = true }
cw-utils = { workspace = true }
cw20-base = { workspace = true, features = ["library"] }
cw2 = { workspace = true }
thiserror = { workspace = true }
cw-paginate = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
