name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      ADMIN_ADDR: juno10j9gpw9t4jsz47qgnkvl5n3zlm2fz72k67rxsg
      GAS_OUT_DIR: gas_reports
      CONFIG: configs/ci.yaml
      CONTRACT_DIR: ../../artifacts
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run Local Juno Node
        run: |
          docker run --rm -d --name juno \
            -e PASSWORD=xxxxxxxxx \
            -e STAKE_TOKEN=ujunox \
            -e GAS_LIMIT=100000000 \
            -e MAX_BYTES=22020096 \
            -e UNSAFE_CORS=true \
            -p 1317:1317 \
            -p 26656:26656 \
            -p 26657:26657 \
            -p 9090:9090 \
            ghcr.io/cosmoscontracts/juno:v9.0.0 /opt/setup_and_run.sh $ADMIN_ADDR

      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # NOTE: Im just trying to compare the CI runtimes of optimzoor and workspace-optimizer
      # using the rust cargo cache

      - name: Build + Optimize contracts
        run: docker run --rm -v "$(pwd)":/code \
              --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
              --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
              --platform linux/amd64 \
              cosmwasm/workspace-optimizer:0.12.6

      - name: Download smart contract dependencies
        run: |
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.11.1/cw20_base.wasm \
            -O artifacts/cw20_base.wasm
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.11.1/cw4_group.wasm \
            -O artifacts/cw4_group.wasm

      - name: Run Integration Tests
        run: RUST_LOG=info cargo integration-test

      - name: Combine Test Gas Reports
        run: cd ci/integration_tests/ && jq -rs 'reduce .[] as $item ({}; . * $item)' gas_reports/*.json > gas_report.json

      - name: Raw Gas Report
        run: cat ci/integration_tests/gas_report.json

      - name: Set GIT_BRANCH
        run: echo "GIT_BRANCH=$(echo ${{ github.ref }} | sed 's|/|-|g')" >> $GITHUB_ENV

      - name: Upload Gas Report
        uses: actions/upload-artifact@v3
        with:
          name: dao-dao-gas-report-${{ env.GIT_BRANCH }}
          path: ci/integration_tests/gas_report.json
          retention-days: 90

      # TODO: Download main's gas_report artifact and diff
